# Generated by Django 4.0.3 on 2022-03-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ovr',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(default=60, max_length=20),
            preserve_default=False,
        ),
    ]
